/**
 * Copyright (C) 2016 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.strata.product.fx;

import java.io.Serializable;
import java.time.LocalDate;
import java.time.ZonedDateTime;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Optional;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanDefinition;
import org.joda.beans.ImmutableBean;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.opengamma.strata.basics.LongShort;
import com.opengamma.strata.basics.currency.Currency;
import com.opengamma.strata.basics.currency.CurrencyPair;
import com.opengamma.strata.basics.date.BusinessDayAdjustment;
import com.opengamma.strata.basics.market.ReferenceData;
import com.opengamma.strata.basics.market.Resolvable;
import com.opengamma.strata.product.Product;

@BeanDefinition
public class FxOneTouchOption
    implements Product, Resolvable<ResolvedFxOneTouchOption>, ImmutableBean, Serializable {

  @PropertyDefinition(validate = "notNull")
  private final LongShort longShort;
  /**
   * The expiry date-time of the option.
   * <p>
   * The option is European, and can only be exercised on the expiry date.
   */
  @PropertyDefinition(validate = "notNull")
  private final ZonedDateTime expiry;

  @PropertyDefinition(validate = "notNull")
  private final LocalDate paymentDate;
  /**
   * The payment date adjustment, optional.
   * <p>
   * If present, the adjustment will be applied to the payment date.
   */
  @PropertyDefinition(get = "optional")
  private final BusinessDayAdjustment paymentDateAdjustment;

  @PropertyDefinition(validate = "notNull")
  private final Currency payoffCurrency;

  @PropertyDefinition(validate = "notNull")
  private final CurrencyPair currencyPair;

  @PropertyDefinition(validate = "notNull")
  private final Barrier barrier;

  @Override
  public ResolvedFxOneTouchOption resolve(ReferenceData refData) {
    LocalDate date = paymentDateAdjustment != null ? paymentDateAdjustment.adjust(paymentDate, refData) : paymentDate;
    return ResolvedFxOneTouchOption.of(longShort, expiry, date, payoffCurrency, currencyPair, barrier);
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code FxOneTouchOption}.
   * @return the meta-bean, not null
   */
  public static FxOneTouchOption.Meta meta() {
    return FxOneTouchOption.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(FxOneTouchOption.Meta.INSTANCE);
  }

  /**
   * The serialization version id.
   */
  private static final long serialVersionUID = 1L;

  /**
   * Returns a builder used to create an instance of the bean.
   * @return the builder, not null
   */
  public static FxOneTouchOption.Builder builder() {
    return new FxOneTouchOption.Builder();
  }

  /**
   * Restricted constructor.
   * @param builder  the builder to copy from, not null
   */
  protected FxOneTouchOption(FxOneTouchOption.Builder builder) {
    JodaBeanUtils.notNull(builder.longShort, "longShort");
    JodaBeanUtils.notNull(builder.expiry, "expiry");
    JodaBeanUtils.notNull(builder.paymentDate, "paymentDate");
    JodaBeanUtils.notNull(builder.payoffCurrency, "payoffCurrency");
    JodaBeanUtils.notNull(builder.currencyPair, "currencyPair");
    JodaBeanUtils.notNull(builder.barrier, "barrier");
    this.longShort = builder.longShort;
    this.expiry = builder.expiry;
    this.paymentDate = builder.paymentDate;
    this.paymentDateAdjustment = builder.paymentDateAdjustment;
    this.payoffCurrency = builder.payoffCurrency;
    this.currencyPair = builder.currencyPair;
    this.barrier = builder.barrier;
  }

  @Override
  public FxOneTouchOption.Meta metaBean() {
    return FxOneTouchOption.Meta.INSTANCE;
  }

  @Override
  public <R> Property<R> property(String propertyName) {
    return metaBean().<R>metaProperty(propertyName).createProperty(this);
  }

  @Override
  public Set<String> propertyNames() {
    return metaBean().metaPropertyMap().keySet();
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the longShort.
   * @return the value of the property, not null
   */
  public LongShort getLongShort() {
    return longShort;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the expiry date-time of the option.
   * <p>
   * The option is European, and can only be exercised on the expiry date.
   * @return the value of the property, not null
   */
  public ZonedDateTime getExpiry() {
    return expiry;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the paymentDate.
   * @return the value of the property, not null
   */
  public LocalDate getPaymentDate() {
    return paymentDate;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the payment date adjustment, optional.
   * <p>
   * If present, the adjustment will be applied to the payment date.
   * @return the optional value of the property, not null
   */
  public Optional<BusinessDayAdjustment> getPaymentDateAdjustment() {
    return Optional.ofNullable(paymentDateAdjustment);
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the payoffCurrency.
   * @return the value of the property, not null
   */
  public Currency getPayoffCurrency() {
    return payoffCurrency;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the currencyPair.
   * @return the value of the property, not null
   */
  public CurrencyPair getCurrencyPair() {
    return currencyPair;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the barrier.
   * @return the value of the property, not null
   */
  public Barrier getBarrier() {
    return barrier;
  }

  //-----------------------------------------------------------------------
  /**
   * Returns a builder that allows this bean to be mutated.
   * @return the mutable builder, not null
   */
  public Builder toBuilder() {
    return new Builder(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      FxOneTouchOption other = (FxOneTouchOption) obj;
      return JodaBeanUtils.equal(longShort, other.longShort) &&
          JodaBeanUtils.equal(expiry, other.expiry) &&
          JodaBeanUtils.equal(paymentDate, other.paymentDate) &&
          JodaBeanUtils.equal(paymentDateAdjustment, other.paymentDateAdjustment) &&
          JodaBeanUtils.equal(payoffCurrency, other.payoffCurrency) &&
          JodaBeanUtils.equal(currencyPair, other.currencyPair) &&
          JodaBeanUtils.equal(barrier, other.barrier);
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash = hash * 31 + JodaBeanUtils.hashCode(longShort);
    hash = hash * 31 + JodaBeanUtils.hashCode(expiry);
    hash = hash * 31 + JodaBeanUtils.hashCode(paymentDate);
    hash = hash * 31 + JodaBeanUtils.hashCode(paymentDateAdjustment);
    hash = hash * 31 + JodaBeanUtils.hashCode(payoffCurrency);
    hash = hash * 31 + JodaBeanUtils.hashCode(currencyPair);
    hash = hash * 31 + JodaBeanUtils.hashCode(barrier);
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(256);
    buf.append("FxOneTouchOption{");
    int len = buf.length();
    toString(buf);
    if (buf.length() > len) {
      buf.setLength(buf.length() - 2);
    }
    buf.append('}');
    return buf.toString();
  }

  protected void toString(StringBuilder buf) {
    buf.append("longShort").append('=').append(JodaBeanUtils.toString(longShort)).append(',').append(' ');
    buf.append("expiry").append('=').append(JodaBeanUtils.toString(expiry)).append(',').append(' ');
    buf.append("paymentDate").append('=').append(JodaBeanUtils.toString(paymentDate)).append(',').append(' ');
    buf.append("paymentDateAdjustment").append('=').append(JodaBeanUtils.toString(paymentDateAdjustment)).append(',').append(' ');
    buf.append("payoffCurrency").append('=').append(JodaBeanUtils.toString(payoffCurrency)).append(',').append(' ');
    buf.append("currencyPair").append('=').append(JodaBeanUtils.toString(currencyPair)).append(',').append(' ');
    buf.append("barrier").append('=').append(JodaBeanUtils.toString(barrier)).append(',').append(' ');
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code FxOneTouchOption}.
   */
  public static class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code longShort} property.
     */
    private final MetaProperty<LongShort> longShort = DirectMetaProperty.ofImmutable(
        this, "longShort", FxOneTouchOption.class, LongShort.class);
    /**
     * The meta-property for the {@code expiry} property.
     */
    private final MetaProperty<ZonedDateTime> expiry = DirectMetaProperty.ofImmutable(
        this, "expiry", FxOneTouchOption.class, ZonedDateTime.class);
    /**
     * The meta-property for the {@code paymentDate} property.
     */
    private final MetaProperty<LocalDate> paymentDate = DirectMetaProperty.ofImmutable(
        this, "paymentDate", FxOneTouchOption.class, LocalDate.class);
    /**
     * The meta-property for the {@code paymentDateAdjustment} property.
     */
    private final MetaProperty<BusinessDayAdjustment> paymentDateAdjustment = DirectMetaProperty.ofImmutable(
        this, "paymentDateAdjustment", FxOneTouchOption.class, BusinessDayAdjustment.class);
    /**
     * The meta-property for the {@code payoffCurrency} property.
     */
    private final MetaProperty<Currency> payoffCurrency = DirectMetaProperty.ofImmutable(
        this, "payoffCurrency", FxOneTouchOption.class, Currency.class);
    /**
     * The meta-property for the {@code currencyPair} property.
     */
    private final MetaProperty<CurrencyPair> currencyPair = DirectMetaProperty.ofImmutable(
        this, "currencyPair", FxOneTouchOption.class, CurrencyPair.class);
    /**
     * The meta-property for the {@code barrier} property.
     */
    private final MetaProperty<Barrier> barrier = DirectMetaProperty.ofImmutable(
        this, "barrier", FxOneTouchOption.class, Barrier.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "longShort",
        "expiry",
        "paymentDate",
        "paymentDateAdjustment",
        "payoffCurrency",
        "currencyPair",
        "barrier");

    /**
     * Restricted constructor.
     */
    protected Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case 116685664:  // longShort
          return longShort;
        case -1289159373:  // expiry
          return expiry;
        case -1540873516:  // paymentDate
          return paymentDate;
        case 737375073:  // paymentDateAdjustment
          return paymentDateAdjustment;
        case -243533576:  // payoffCurrency
          return payoffCurrency;
        case 1005147787:  // currencyPair
          return currencyPair;
        case -333143113:  // barrier
          return barrier;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public FxOneTouchOption.Builder builder() {
      return new FxOneTouchOption.Builder();
    }

    @Override
    public Class<? extends FxOneTouchOption> beanType() {
      return FxOneTouchOption.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code longShort} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<LongShort> longShort() {
      return longShort;
    }

    /**
     * The meta-property for the {@code expiry} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<ZonedDateTime> expiry() {
      return expiry;
    }

    /**
     * The meta-property for the {@code paymentDate} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<LocalDate> paymentDate() {
      return paymentDate;
    }

    /**
     * The meta-property for the {@code paymentDateAdjustment} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<BusinessDayAdjustment> paymentDateAdjustment() {
      return paymentDateAdjustment;
    }

    /**
     * The meta-property for the {@code payoffCurrency} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<Currency> payoffCurrency() {
      return payoffCurrency;
    }

    /**
     * The meta-property for the {@code currencyPair} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<CurrencyPair> currencyPair() {
      return currencyPair;
    }

    /**
     * The meta-property for the {@code barrier} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<Barrier> barrier() {
      return barrier;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case 116685664:  // longShort
          return ((FxOneTouchOption) bean).getLongShort();
        case -1289159373:  // expiry
          return ((FxOneTouchOption) bean).getExpiry();
        case -1540873516:  // paymentDate
          return ((FxOneTouchOption) bean).getPaymentDate();
        case 737375073:  // paymentDateAdjustment
          return ((FxOneTouchOption) bean).paymentDateAdjustment;
        case -243533576:  // payoffCurrency
          return ((FxOneTouchOption) bean).getPayoffCurrency();
        case 1005147787:  // currencyPair
          return ((FxOneTouchOption) bean).getCurrencyPair();
        case -333143113:  // barrier
          return ((FxOneTouchOption) bean).getBarrier();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      metaProperty(propertyName);
      if (quiet) {
        return;
      }
      throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
    }

  }

  //-----------------------------------------------------------------------
  /**
   * The bean-builder for {@code FxOneTouchOption}.
   */
  public static class Builder extends DirectFieldsBeanBuilder<FxOneTouchOption> {

    private LongShort longShort;
    private ZonedDateTime expiry;
    private LocalDate paymentDate;
    private BusinessDayAdjustment paymentDateAdjustment;
    private Currency payoffCurrency;
    private CurrencyPair currencyPair;
    private Barrier barrier;

    /**
     * Restricted constructor.
     */
    protected Builder() {
    }

    /**
     * Restricted copy constructor.
     * @param beanToCopy  the bean to copy from, not null
     */
    protected Builder(FxOneTouchOption beanToCopy) {
      this.longShort = beanToCopy.getLongShort();
      this.expiry = beanToCopy.getExpiry();
      this.paymentDate = beanToCopy.getPaymentDate();
      this.paymentDateAdjustment = beanToCopy.paymentDateAdjustment;
      this.payoffCurrency = beanToCopy.getPayoffCurrency();
      this.currencyPair = beanToCopy.getCurrencyPair();
      this.barrier = beanToCopy.getBarrier();
    }

    //-----------------------------------------------------------------------
    @Override
    public Object get(String propertyName) {
      switch (propertyName.hashCode()) {
        case 116685664:  // longShort
          return longShort;
        case -1289159373:  // expiry
          return expiry;
        case -1540873516:  // paymentDate
          return paymentDate;
        case 737375073:  // paymentDateAdjustment
          return paymentDateAdjustment;
        case -243533576:  // payoffCurrency
          return payoffCurrency;
        case 1005147787:  // currencyPair
          return currencyPair;
        case -333143113:  // barrier
          return barrier;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
    }

    @Override
    public Builder set(String propertyName, Object newValue) {
      switch (propertyName.hashCode()) {
        case 116685664:  // longShort
          this.longShort = (LongShort) newValue;
          break;
        case -1289159373:  // expiry
          this.expiry = (ZonedDateTime) newValue;
          break;
        case -1540873516:  // paymentDate
          this.paymentDate = (LocalDate) newValue;
          break;
        case 737375073:  // paymentDateAdjustment
          this.paymentDateAdjustment = (BusinessDayAdjustment) newValue;
          break;
        case -243533576:  // payoffCurrency
          this.payoffCurrency = (Currency) newValue;
          break;
        case 1005147787:  // currencyPair
          this.currencyPair = (CurrencyPair) newValue;
          break;
        case -333143113:  // barrier
          this.barrier = (Barrier) newValue;
          break;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
      return this;
    }

    @Override
    public Builder set(MetaProperty<?> property, Object value) {
      super.set(property, value);
      return this;
    }

    @Override
    public Builder setString(String propertyName, String value) {
      setString(meta().metaProperty(propertyName), value);
      return this;
    }

    @Override
    public Builder setString(MetaProperty<?> property, String value) {
      super.setString(property, value);
      return this;
    }

    @Override
    public Builder setAll(Map<String, ? extends Object> propertyValueMap) {
      super.setAll(propertyValueMap);
      return this;
    }

    @Override
    public FxOneTouchOption build() {
      return new FxOneTouchOption(this);
    }

    //-----------------------------------------------------------------------
    /**
     * Sets the longShort.
     * @param longShort  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder longShort(LongShort longShort) {
      JodaBeanUtils.notNull(longShort, "longShort");
      this.longShort = longShort;
      return this;
    }

    /**
     * Sets the expiry date-time of the option.
     * <p>
     * The option is European, and can only be exercised on the expiry date.
     * @param expiry  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder expiry(ZonedDateTime expiry) {
      JodaBeanUtils.notNull(expiry, "expiry");
      this.expiry = expiry;
      return this;
    }

    /**
     * Sets the paymentDate.
     * @param paymentDate  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder paymentDate(LocalDate paymentDate) {
      JodaBeanUtils.notNull(paymentDate, "paymentDate");
      this.paymentDate = paymentDate;
      return this;
    }

    /**
     * Sets the payment date adjustment, optional.
     * <p>
     * If present, the adjustment will be applied to the payment date.
     * @param paymentDateAdjustment  the new value
     * @return this, for chaining, not null
     */
    public Builder paymentDateAdjustment(BusinessDayAdjustment paymentDateAdjustment) {
      this.paymentDateAdjustment = paymentDateAdjustment;
      return this;
    }

    /**
     * Sets the payoffCurrency.
     * @param payoffCurrency  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder payoffCurrency(Currency payoffCurrency) {
      JodaBeanUtils.notNull(payoffCurrency, "payoffCurrency");
      this.payoffCurrency = payoffCurrency;
      return this;
    }

    /**
     * Sets the currencyPair.
     * @param currencyPair  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder currencyPair(CurrencyPair currencyPair) {
      JodaBeanUtils.notNull(currencyPair, "currencyPair");
      this.currencyPair = currencyPair;
      return this;
    }

    /**
     * Sets the barrier.
     * @param barrier  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder barrier(Barrier barrier) {
      JodaBeanUtils.notNull(barrier, "barrier");
      this.barrier = barrier;
      return this;
    }

    //-----------------------------------------------------------------------
    @Override
    public String toString() {
      StringBuilder buf = new StringBuilder(256);
      buf.append("FxOneTouchOption.Builder{");
      int len = buf.length();
      toString(buf);
      if (buf.length() > len) {
        buf.setLength(buf.length() - 2);
      }
      buf.append('}');
      return buf.toString();
    }

    protected void toString(StringBuilder buf) {
      buf.append("longShort").append('=').append(JodaBeanUtils.toString(longShort)).append(',').append(' ');
      buf.append("expiry").append('=').append(JodaBeanUtils.toString(expiry)).append(',').append(' ');
      buf.append("paymentDate").append('=').append(JodaBeanUtils.toString(paymentDate)).append(',').append(' ');
      buf.append("paymentDateAdjustment").append('=').append(JodaBeanUtils.toString(paymentDateAdjustment)).append(',').append(' ');
      buf.append("payoffCurrency").append('=').append(JodaBeanUtils.toString(payoffCurrency)).append(',').append(' ');
      buf.append("currencyPair").append('=').append(JodaBeanUtils.toString(currencyPair)).append(',').append(' ');
      buf.append("barrier").append('=').append(JodaBeanUtils.toString(barrier)).append(',').append(' ');
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
